baseURL = 'https://myblog-47x.pages.dev/'
title = 'Zechao Jin'
languageCode = 'en-us'
theme = ["hugo-theme-stack", "almeida-cv"]


[params.sidebar.avatar]
enabled = true
local = true
src = "img/zechao.jpg"

[params.article]
math = true
toc = true
readingTime = true
license.enabled = true
license.default = "Licensed under CC BY-NC-SA 4.0"

[params.widgets]
homepage = [
    { type = "search" },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
]
page = [{ type = "toc" }]

[params]
# param for almeida-cv
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = true


[params.comments]
enabled = true
provider = "disqus"