baseURL = 'https://www.devzechao.com/'
title = 'Zechao Jin'
languageCode = 'en-us'
theme = ["hugo-theme-stack", "almeida-cv"]


[params.sidebar.avatar]
enabled = true
local = true
src = "img/zechao.jpg"

[params.article]
math = true
toc = true
readingTime = true
license.enabled = true
license.default = "Licensed under CC BY-NC-SA 4.0"

[params.widgets]
homepage = [
    { type = "search" },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
]
page = [{ type = "toc" }]




